-- Sample data for Ten12 Portfolio
-- Run this after setup_database.sql to populate with sample projects

INSERT INTO projects (title, description, content, thumbnail, images, category, tags, live_url, github_url, published) VALUES 
('E-Commerce Platform', 'A modern e-commerce solution with advanced features', 'This comprehensive e-commerce platform was built from the ground up to provide a seamless shopping experience. The project features a responsive design, secure payment processing, inventory management, and real-time order tracking. We implemented advanced search functionality, user reviews, and personalized recommendations to enhance the shopping experience. The backend handles thousands of products and can scale to meet growing business needs.', 'uploads/ecommerce-thumb.jpg', '["uploads/ecommerce-1.jpg", "uploads/ecommerce-2.jpg", "uploads/ecommerce-3.jpg"]', 'Web', 'PHP, MySQL, JavaScript, Bootstrap, Stripe API', 'https://demo-ecommerce.example.com', 'https://github.com/ten12/ecommerce-platform', 1),

('Mobile Banking App', 'Secure and intuitive mobile banking application', 'A comprehensive mobile banking application designed with security and user experience as top priorities. The app features biometric authentication, real-time transaction monitoring, budget tracking, and personalized financial insights. We implemented end-to-end encryption and multi-factor authentication to ensure the highest level of security for user data. The intuitive interface makes complex banking operations simple and accessible for all users.', 'uploads/banking-thumb.jpg', '["uploads/banking-1.jpg", "uploads/banking-2.jpg"]', 'Mobile', 'React Native, Node.js, MongoDB, JWT, Biometric API', 'https://demo-banking.example.com', 'https://github.com/ten12/mobile-banking', 1),

('Brand Identity System', 'Complete brand identity design for tech startup', 'A complete brand identity system created for an innovative tech startup. This project included logo design, color palette development, typography selection, and comprehensive brand guidelines. We created a versatile visual system that works across digital and print media, ensuring consistent brand representation. The identity reflects the company\'s innovative spirit while maintaining professional credibility in the competitive tech market.', 'uploads/brand-thumb.jpg', '["uploads/brand-1.jpg", "uploads/brand-2.jpg", "uploads/brand-3.jpg", "uploads/brand-4.jpg"]', 'Design', 'Adobe Creative Suite, Figma, Brand Strategy', '', '', 1),

('Task Management Dashboard', 'Collaborative project management solution', 'A powerful task management dashboard designed to streamline team collaboration and project tracking. The platform features real-time updates, drag-and-drop functionality, time tracking, and comprehensive reporting. We implemented an intuitive Kanban board system with customizable workflows and automated notifications. The solution helps teams increase productivity by providing clear visibility into project progress and resource allocation.', 'uploads/dashboard-thumb.jpg', '["uploads/dashboard-1.jpg", "uploads/dashboard-2.jpg"]', 'Web', 'Vue.js, Express.js, PostgreSQL, Socket.io, Chart.js', 'https://demo-dashboard.example.com', 'https://github.com/ten12/task-dashboard', 1),

('Social Media Analytics', 'Advanced analytics platform for social media management', 'A sophisticated analytics platform that provides comprehensive insights into social media performance. The system tracks engagement metrics, audience demographics, and content performance across multiple social networks. We implemented machine learning algorithms to predict trending topics and optimal posting times. The intuitive dashboard presents complex data in easy-to-understand visualizations, helping marketers make data-driven decisions.', 'uploads/analytics-thumb.jpg', '["uploads/analytics-1.jpg", "uploads/analytics-2.jpg", "uploads/analytics-3.jpg"]', 'Web', 'Python, Django, React, D3.js, TensorFlow', 'https://demo-analytics.example.com', 'https://github.com/ten12/social-analytics', 1),

('Restaurant Booking System', 'Modern reservation system for hospitality industry', 'A comprehensive restaurant booking system that streamlines reservation management for both customers and restaurant staff. The platform features real-time availability checking, table management, customer preferences, and automated reminders. We developed a mobile-responsive interface that works seamlessly on all devices. The system helps restaurants optimize seating arrangements and improve customer satisfaction through efficient booking processes.', 'uploads/restaurant-thumb.jpg', '["uploads/restaurant-1.jpg", "uploads/restaurant-2.jpg"]', 'Web', 'PHP, Laravel, MySQL, Twilio API, Google Maps', 'https://demo-restaurant.example.com', 'https://github.com/ten12/restaurant-booking', 1);

-- Add sample contact messages
INSERT INTO contacts (name, email, message) VALUES 
('John Smith', 'john.smith@example.com', 'I\'m impressed with your portfolio! I\'d like to discuss a potential project for my company. Do you have availability for a consultation next week?'),
('Sarah Johnson', 'sarah.j@startup.com', 'Your e-commerce platform looks exactly like what we need for our business. Can you provide more information about customization options and pricing?'),
('Mike Chen', 'mike.chen@techcorp.io', 'Great work on the mobile banking app! We\'re looking for a similar solution for our fintech startup. Would love to schedule a call to discuss requirements.'),
('Emily Davis', 'emily@marketingagency.com', 'The brand identity work is outstanding! We have several clients who would benefit from your design services. Can we set up a partnership discussion?'),
('Alex Thompson', 'alex@restaurant.com', 'The restaurant booking system looks perfect for our growing chain. Do you offer multi-location support and staff training?');

-- Update site settings
UPDATE settings SET setting_value = 'Ten12 - Modern Portfolio & Design Studio' WHERE setting_key = 'site_title';
UPDATE settings SET setting_value = 'Creating exceptional digital experiences with clean design and powerful functionality.' WHERE setting_key = 'site_description';
UPDATE settings SET setting_value = '{"github": "https://github.com/ten12", "linkedin": "https://linkedin.com/company/ten12", "twitter": "https://twitter.com/ten12studio"}' WHERE setting_key = 'social_links';
